import { NextPage } from "next";
import React, { ReactNode, useEffect, useRef } from "react";
import Header from "@/components/Layout/Header";
import Head from "next/head";
import Footer from "@/components/Layout/Footer";
import moment from "moment";
import NavMobile from "@/components/Layout/NavMobile";
import { useAppSelector } from "@/redux/hook";
import OrderModal from "@/components/Modal/OrderModal";
import Backdrop from "@/components/Modal/Backdrop";

const Layout: NextPage<{
  children: ReactNode;
  title?: string;
}> = ({ children, title }) => {
  const { orderModal } = useAppSelector((state) => state.orderSlice);
  const { isOpenBackdrop } = useAppSelector((state) => state.isSlice);
  useEffect(() => {
    moment.locale("vi");
  }, []);

  return (
    <>
      <Head>
        <title>{title ? title : "ChiChi - Shop"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./favicon.png" />
      </Head>
      <NavMobile />
      {isOpenBackdrop && <Backdrop />}
      {orderModal.isOpen && <OrderModal />}
      <div className="relative bg-white w-screen h-screen overflow-y-scroll scrollbar-thin scrollbar-thumb-gray-400 scrollbar-track-gray-100 overflow-x-hidden">
        <Header />
        {children}
        <Footer />
      </div>
    </>
  );
};

export default Layout;
