import { NextPage } from 'next'
import React, { ReactNode } from 'react'
import Header from '@/components/Layout/Header'
import Head from 'next/head'
import Footer from '@/components/Layout/Footer'

const Layout:NextPage<{
    children: ReactNode
}> = ({children}) => {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className="bg-white w-screen h-screen overflow-y-scroll scrollbar-thin scrollbar-thumb-gray-400 scrollbar-track-gray-100 overflow-x-hidden">
        <Header />
        {children}
        <Footer />
    </div>
    </>
  )
}

export default Layout